### ISSUE TITLE
[PLAN] 기프티콘 등록 - 금액권, 메모 스토리보드 내용 누락

### ISSUE THREAD

**Issue by voidtheart** [YAPP-Github/21st-Android-Team-1-Android#102]
## 위치
쿠폰 상세화면 - 공통사항 - 기프티콘 등록: 정보 입력 완료

## 전달사항 
1. 기프티콘 등록 화면에서 메모 / 금액권 내용이 스토리보드에 누락되어있어서 전달 드립니다 
(요앞전부터 이야기는 여러차례 나누어서 아마 개발에 문제는 없으셨을 것 같은데 혹시나해서 공유드립니다ㅠㅠ 죄송합니다!)

<img width="552" alt="스크린샷 2023-02-23 오후 11 01 30" src="https://user-images.githubusercontent.com/121834419/220929869-ab6054ee-c99c-4ace-a2c2-8ec96c1b798d.png">

**Comment by ows3090** [comment]
@voidtheart 선아님
해당 내용은 인지하고 개발했어서 클로즈하겠습니다!

**Comment by voidtheart** [comment]
@ows3090 
원석님
헉 제가 놓쳐서 걱정했는데 ㅠㅠㅠㅠ 감사합니다 🥺
