### ISSUE TITLE
[Question] StateFlow 사용 시 '타입을 명시하는 방법' VS 'asStateFlow' 차이는???

### ISSUE THREAD

**Issue by hanchang97** [YAPP-Github/21st-Android-Team-1-Android#14]
## 관련된 기능
> 개발하면서 생긴 궁금증

## 문제
> 1. StateFlow 사용 시 타입을 명시하는 방법 VS asStateFlow 차이는???

**Comment by ows3090** [comment]
@hanchang97 @ashwon12 
(https://stackoverflow.com/questions/73987849/what-is-the-difference-between-uistate-asstateflow-and-stateflowuistate)
참고하면 좋을 것 같습니다.
![image](https://user-images.githubusercontent.com/34837583/211616010-25189def-0f11-454e-822a-3ff8c04aa28f.png)

**Comment by ows3090** [comment]
@hanchang97 @ashwon12 추후 하는 것으로 하고 이슈 종료하겠습니다.
