### ISSUE TITLE
[Question] 자체 서버 AccessToken 관리

### ISSUE THREAD

**Issue by ows3090** [YAPP-Github/21st-Android-Team-1-Android#15]
## 문제
> 저희 서버 API 요청 시에 AccessToken 관리 어떻게 하시나요?
Retrofit Service 인터페이스마다 Header로 하시는지 Interceptor를 사용하는지 궁금합니다~

**Comment by ows3090** [comment]
@ashwon12 @hanchang97 
그리고 저희 카카오 서버 이용하는 것을 제외하고는 모두 자체 서버 사용할 것 같은데 BuddyConRepository만 있으면 되겠죠?
Repository를 더 세부적으로 나눈다던가 하는 의견 있으시면 말씀해주세요~

**Comment by hanchang97** [comment]
api 명세가 조금 더 구체적으로 나오면 기능 및 데이터 별로 분리하는 것도 괜찮아 보입니다!
