### ISSUE TITLE
[Design] 러브레터 이미지 변경

### ISSUE THREAD

**Issue by 101tjgus** [YAPP-Github/21st-Android-Team-1-Android#25]
### 목적
> 기프티콘, 제작티콘 화면에서 쿠폰 데이터가 없을 때 뜨는 러브레터 이미지
화면과 어울리지 않아 일러스트를 조금 다듬어 대체했습니다.

### 변경사항
러브레터 이미지를 변경합니다

as-is: 꽃분홍
<img width="138" alt="스크린샷 2023-01-18 오후 11 50 18" src="https://user-images.githubusercontent.com/121834419/213202885-bba05d69-207f-4890-aef8-1ec4cbf72654.png">

to-be: 연한 핑크색
<img width="144" alt="스크린샷 2023-01-18 오후 11 49 00" src="https://user-images.githubusercontent.com/121834419/213202580-73f006dc-4b20-41bd-ae97-3878d8349bea.png">

### 위치 
(=수정 필요한 페이지)

1. 기프티콘
1-1)  기프티콘 - 사용가능 탭 (데이터 없을 때)
1-2) 기프티콘 - 사용완료 탭 (데이터 없을 때)

2. 제작티콘
2-1) 제작티콘 - 사용가능 탭 (데이터 없을 때)
2-2) 제작티콘 - 사용완료 탭 (데이터 없을 때)
2-3) 제작티콘 - 만든쿠폰 탭 (데이터 없을 때)

3. 제작티콘 만들기
3-1) 첫번째 테마 기본 이미지
3-2) 테마 펼쳤을 때 보이는 미리보기 이미지

- [ ] **수정한 이미지로 대체**해주시면 감사하겠습니다 :)

### 참고 사항
위에 나열한 페이지들은
**피그마 '디자인 최종' 페이지에서 초록색 라인 박스로 표시**해두었습니다!
감사합니다.

**Comment by 101tjgus** [comment]
라벨 수정하는 방법을 모르겠어서... 라벨 바꾸는 법 한번 찾아보고 디자인으로 수정하겠습니다...

**Comment by voidtheart** [comment]
@hanchang97 창희님이 얼럿 파트 담당이신 것 같아서 우선 어사인드립니당!

**Comment by ows3090** [comment]
@voidtheart 선아님
얼럿과  상관이 있는건가요?
해당 기능은 제가  담당해야 할 것 같습니다.

**Comment by voidtheart** [comment]
> @voidtheart 선아님 얼럿과 상관이 있는건가요? 해당 기능은 제가 담당해야 할 것 같습니다.

아 헙 얼럿과 무관합니다! 제가 정신이 없어서 얼럿으로 순간 착각했네요 ㅠㅠ 빈화면이라서 원석님 파트인 것 같습니다. 담당자 변경하겠습니다!

**Comment by ashwon12** [comment]
변경된 이미지로 리소스 등록해서 close 합니다. 
@ows3090  
`drawable/img_theme1` 파일입니다~ 이거 사용하시면 돼요!
