### ISSUE TITLE
[Design] 플로팅 버튼에 대한 코치마크 위치/텍스트 변경

### ISSUE THREAD

**Issue by 101tjgus** [YAPP-Github/21st-Android-Team-1-Android#26]
### 위치 
로그인 - 기프트콘 (최초 진입)
(노출 조건: 회원가입 완료한 다음, 기프티콘 진입한 최초 시점) 

### 기존사항
1. [제작티콘 페이지]에 있었던 플로팅 버튼(+)에 대한 코치마크가 회원가입 완료 이후 최초 진입 시점에 노출됩니다. 
(코치마크 문구: +에서 ‘제작티콘 만들기’를 눌러 나만의 쿠폰을 만들어 보세요!)

### 변경사항 
1. [기프티콘 페이지]에서 플로팅 버튼(+)에 대한 코치마크가 회원가입 완료 이후 최초 진입 시점에 노출됩니다.
(코치마크 문구: 가지고 있는 쿠폰을 등록하거나나
<img width="495" alt="스크린샷 2023-02-04 오후 10 37 35" src="https://user-images.githubusercontent.com/121834419/216770756-8927d6b2-ae63-4ab4-8c98-0e3dbc0c13a1.png">
만의 쿠폰을 만들 수 있어요)

### 기대효과
1. [기프티콘 페이지]에서 플로팅 버튼(+)에 대한 코치마크가 회원가입 완료 이후 최초 진입 시점에 노출됩니다.

### 참고사항 
해당 화면은 피그마 '디자인 최종' 페이지에서
**파란색 라인 박스**로 표시해 두었습니다.
감사합니다.

**Comment by voidtheart** [comment]
@hanchang97 @ows3090 뭔가 담당파트가 두분 중 한분 이실 것 같아서 두분 모두 어사인드립니다. 확인하시고 어사인 제거해주시면 되어요!

@101tjgus 저랑 텍스트 픽스되면 gui랑 텍스트 변경사항 최종적으로 전달드리는거로 할게요!

**Comment by ows3090** [comment]
@voidtheart 네  텍스트 픽스되면 노티 부탁드립니다

**Comment by ows3090** [comment]
@voidtheart @101tjgus 선아님, 서현님
Walk Through 정책과 코치마크 정책이 동일하게 가는 것에 대한 의견 문의드립니다.

현재 Walk Through는 카카오 로그인 페이지 화면에 한번이라도 진입할 경우에 다시 노출되지 않도록 하고 있습니다.
코치마크는 카카오 로그인을 한번 수행했을 때 노출되고 그 이후는 노출되지 않습니다.

만일, 카카오 로그인 페이지만 가고 로그인을 하지 않다가 추후에 실행했다고 하면
Walk Through는 노출되지 않고 카카오 로그인 후 코치마크만 노출되는게 맞을까요?
혹시 Walk Through도 동일하게 최초 로그인 유무로 구별하는 것은 어떨지 의견 문의드립니다.

**Comment by voidtheart** [comment]
@ows3090 
말씀하신 방안 중에서 두번째 (최초 로그인을 기준으로 노출, 이후는 미노출)이 좋을 것 같습니다! 서현님은 혹시 어떠실까요?

**Comment by 101tjgus** [comment]
@ows3090 저도 두번째 방안이 좋은 것 같습니다! 깊게 생각하지 못한 부분이었는데 꼼꼼하게 짚어주셔서 감사합니다

**Comment by ows3090** [comment]
@voidtheart 선아님
코치마크 개발 완료되어 이슈 종료 부탁드립니다 :)

**Comment by voidtheart** [comment]
@101tjgus 
서현님, 개발측 완료되어서 클로즈 전에 지혜님이 작성하신 문구 정해보면 좋을 것 같아서 퀵하게 달아봅니다!
지혜님이 요렇게 두가지로 베리에이션 주셨는데, 혹시 어느 문구가 더 좋으실까요?

(원석님, 문구 정해지는대로 전달드리고 바로 이슈 클로즈하겠습니다! 참고부탁드릴게요 @ows3090)

<img width="389" alt="스크린샷 2023-01-29 오후 10 06 08" src="https://user-images.githubusercontent.com/121834419/215328076-75fa6731-d530-45e3-86e7-751f781b8ee2.png">

**Comment by 101tjgus** [comment]
@voidtheart 오 저는 두번째 '보관'이 조금 더 직관적이고 친절하게 느껴지네요!! 그런데 플러스 버튼을 눌러서 나오는 메뉴명은 '등록'이라서 정확하게 명시하는 점에서는 첫번째 안이 좋은 것 같아서 헷갈리네요... 선아님은 어떠셨나요?

**Comment by voidtheart** [comment]
@101tjgus 
저도 동일하게 느꼈습니다 ㅠㅠ 보관이라는 워딩이 좋은데 이미 서비스에 전체적으로 등록이라고 명시되어있고, 일반적으르 동록이라는 키워드를 쓰는 것 같아서 따뜻한 느낌은 2, 하지만 현실적으로는 1 같았어요! 제가 해당 부분 알림을 놓치고 있어서 지금 답변드립니다ㅠㅠ

**Comment by 101tjgus** [comment]
@voidtheart 네네 정확히 같은 이유로 첫번째 안이 최선인 것 같네요...! 그럼 그렇게 픽스하는걸로 결정할까요?!

**Comment by voidtheart** [comment]
@101tjgus 
넵, 요기서 원석님께 변경 요청드리고 스토리보드 지금 반영하겠습니다!

**Comment by voidtheart** [comment]
@ows3090 
원석님, 해당 이슈에 해당하는 화면의 코치마크 텍스트를 아래와 같이 변경 요청드립니다!
(확인 이후 이슈 클로즈하도록 하겠습니다)

'가지고 있는 쿠폰을 등록하거나
나만의 쿠폰을 만들 수 있어요'

**Comment by voidtheart** [comment]
해당 이슈 클로즈합니당!
(이후 재확인 필요)
