### ISSUE TITLE
[PLAN] 스플래시 - 건너뛰기 기능 추가 

### ISSUE THREAD

**Issue by voidtheart** [YAPP-Github/21st-Android-Team-1-Android#27]
### 위치 
스플래시 - walk through 

### 변경사항 
1. walk through 상단 우측에 '건너뛰기' 버튼을 추가합니다

### 기대효과
1. '건너뛰기' 버턴을 누르면 마지막 walk through 페이지로 한번에 이동합니다 

<img width="829" alt="스크린샷 2023-01-18 오후 11 38 29" src="https://user-images.githubusercontent.com/121834419/213201257-eebbc996-ec4c-458d-9cb1-0979e99441a2.png">

**Comment by voidtheart** [comment]
@Huey-J @shinyubin989 내용 참고부탁드립니다!

**Comment by ows3090** [comment]
@voidtheart 선아님
내용 확인하였습니다.

**Comment by ows3090** [comment]
@voidtheart 선아님
Walk Through 부분에서 궁금한 점이 있어서 댓글 남깁니다.
최초 어플리케이션 설치 이후 Walk Through 지나고 카카오 로그인 화면까지 갔습니다.
하지만 로그인을 하지 않고 그냥 종료한 경우에 다시 실행 시 Walk Through를 보여주는 걸까요?
아니면 한번이라도 카카오 로그인 페이지를 가면 Walk Through 안보여주는 걸까요?

**Comment by voidtheart** [comment]
@ows3090 
한번이라도 로그인 페이지에 도달했다면 walk through가 노출되지 않는게 사용성은 좋긴 합니담..!
근데 개발적으로 시간이 더 걸리면 상시 노출해도 괜찮습니다 🙂

**Comment by ows3090** [comment]
@voidtheart 
아닙니다. 정책에 맞게 개발하도록 할게요 :)

**Comment by voidtheart** [comment]
@ows3090 
작업하시다가 힘드시면 언제든지 스펙 조정 가능하니 편하게 말씀주세요! 화이팅입니다 🫡

**Comment by ows3090** [comment]
@voidtheart 선아님
해당 기능 개발 완료되어 이슈 종료하겠습니다!

**Comment by voidtheart** [comment]
@ows3090 
늦은시간까지 고생 많으셨습니다 원석님! 🙂
