### ISSUE TITLE
[PLAN] 로그인 / 회원가입뷰 추가 (약관 동의 / 회원가입 완료 / 코치마크) 

### ISSUE THREAD

**Issue by voidtheart** [YAPP-Github/21st-Android-Team-1-Android#28]
# 위치 
로그인 / 회원가입 
- [ ] 회원가입 / 동의 항목 화면 
- [ ] 회원가입 완료 화면
- [ ] 기프티콘 (최초 진입)

# 추가사항 
(화면이 총 3종류이므로 종류별로 묶어서 작성합니다.)

### 회원가입 / 동의 항목 화면
1. 이용약관 화면이 추가되었습니다
- '모두 동의하기' 버튼을 클릭하여 '이용약관'과 '개인정보 수집 및 이용'에 한번에 동의할 수 있습니다
- '이용약관'에 동의하거나 > 을 눌러서 상세내용을 볼 수 있습니다 (상세페이지 이동)
- '개인정보 수집 및 이용'에 동의하거나 > 을 눌러서 상세내용을 볼 수 있습니다 (상세페이지 이동) 
(공지페이지에 사용되는 화면을 그대로 사용합니다, 개발상 우선순위에 밀리는 경우 노션 링크 연결도 좋습니다 🙂)

### 회원가입 완료 화면
1. 회원가입 / 회원가입 화면이 추가되었습니다
- 별도의 버튼 없이, 4초 노출 이후 '기프티콘' 페이지로 이동합니다

### 기프티콘 코치마크 (최초 진입)
1. 회원 가입 완료 이후, 기프티콘 탭에 최초 진입 시에만 '코치마크'가 노출됩니다.
(상세한 변경사항은 #26 에서 확인 가능)

<img width="1015" alt="스크린샷 2023-01-19 오전 12 28 16" src="https://user-images.githubusercontent.com/121834419/213213173-0f82cfbe-a1aa-47ec-a304-2e3965cae1c8.png">

#참고사항
기획단에서 내용, 디자인단에서 gui 작업이 필요하여 플로우와 스펙만 참고 부탁드리겠습니다 :) 
반영되는 사항들은 해당 이슈 노티로 드릴 예정입니다

### 회원가입 / 동의 화면 
1. 기획 - 닉네임, 연령대는 아마도 선택값으로 받아야할 것 같아서 기획단에서 리서치 이후 필수, 선택값인지 전달드리겠습니다. (노티 예정)
2. 디자인 - 필수항목 미 선택 시, 나타나는 인터랙션 논의가 필요하여 추후 전달드리겠습니다 @101tjgus 

### 회원가입 완료 화면
3. 최종 gui 전달 부탁드립니다 @101tjgus 

### 기프티콘 코치마크 (최초 진입)
4. 코치마크는 #26 에서 전달 드릴 예정입니다.

**Comment by voidtheart** [comment]
@Huey-J @shinyubin989 내용 참고부탁드립니다!

**Comment by ows3090** [comment]
@voidtheart 선아님 회원가입 기능이 새로 생긴걸까요?

**Comment by voidtheart** [comment]
> @voidtheart 선아님 회원가입 기능이 새로 생긴걸까요?

앗 제가 추가라고 제목을 적어서 헷갈리게 한 것 같네요ㅠㅠ 
처음 스토리보드 공유드렸을 때부터 있었는데 (카카오 소셜로그인으로 동일합니담)
다른 기능 기획에 밀려서 이용약관과 회원가입 완료뷰가 지금 나와서 공유드리게 되었습니다!

**Comment by ows3090** [comment]
@voidtheart 선아님
<img width="729" alt="image" src="https://user-images.githubusercontent.com/34837583/213860465-7ba0ca1c-e518-4b23-81b2-91a750d454f4.png">

동의화면은 별도로 구현하지는 못하고 저렇게 카카오 로그인 시에 자동으로 동의화면이 나오게 됩니다.

**Comment by voidtheart** [comment]
@ows3090 
앗 확인 감사합니다..! 

그렇다면 혹시 카카오 동의 화면을 표시한 다음, 어플 내 이용약관 페이지로 이동하는건 가능할까요? 
[아카이브 서비스](https://apps.apple.com/kr/app/archive/id1599941822)에서 회원가입 플로우를 요렇게 진행하고 있는데, 가능한지 여쭤보고 싶어서요..!! 

제가 회원가입 - 탈퇴을 이미 진행했었어서 카카오톡 동의화면은 이미 동의처리된 것 같으니 참고 부탁드립니다! 
https://user-images.githubusercontent.com/121834419/213909706-9193eb7b-62b8-4314-9a52-1f7691f2628a.MP4

해당 이용약관 페이지 이동과 별개로 카카오 동의화면으로 진행해야 할 것 같아서 스토리보드에 반영했습니다 
(이용약관 페이지는 사용성 + 개발 측면 모두 논의한 다음 픽스지으려고 합니당! 
우선은 정리하는 김에 작성했으니 참고해주세요 :D
<img width="1137" alt="스크린샷 2023-01-22 오후 6 45 37" src="https://user-images.githubusercontent.com/121834419/213909761-b0b50638-73e0-4596-8d6d-a78f7efeae12.png">

**Comment by voidtheart** [comment]
@101tjgus 
피그마에서 코멘트로도 작성했지만, 깃에서 논의하는게 히스토리보기 용이할 것 같아서 작성합니당 

아카이브 서비스에서 카카오 계정 로그인 > 이용약관 페이지 > 닉네임 설정 페이지로 이동합니다.

1. 카카오 계정 로그인 > 이용약관 페이지로 넘어가는게 일반적인 플로우인지 의견 궁금합니다. 
뎁스가 약간 깊다는 느낌이 들어서 여쭙습니당 ㅎㅎ
- 일반적이지 않다면, 마이페이지에서 이용약관을 보여주는게 맞을 것 같기도 하고요 🥲

**Comment by ows3090** [comment]
@voidtheart 선아님
위처럼  구현은 가능합니다.
혹시 카카오 닉네임이 아닌 저희 어플용 닉네임을 별도로 설정하는 걸까요?
또한 이용약관, 개인정보 방침에 대한 상세정보 확인 페이지가 별도로 있는지도 문의드립니다.

**Comment by voidtheart** [comment]
@ows3090 
빠른 확인 감사합니다 원석님 🙂
저희는 닉네임 기능이 따로 없어서 아카이브에 나오는 첫 페이지 (이용약관)까지만 참고하시면 될 것 같습니당!
우선 구현은 가능하다고 답변주셨으니 해당 부분 사용성 괜찮을지 서현님께 한번 여쭤보겠습니다! 

이용약관, 개인정보 방침은 제가 설연휴 전후로 작성하여 전달드릴 예정입니다.
따로 페이지를 개발하지 않고, 노션 링크를 걸려고 하는데 괜찮으실까요?

**Comment by 101tjgus** [comment]
@voidtheart 
약관 동의는 카카오톡 회원가입 알럿에서 모두 해결되면 뎁스도 줄어들고 편할 것 같긴 합니다... 
그런데 이용약관을 회원가입할 때 안받고 마이페이지에서 보여만 주는게 가능한건가요?!

**Comment by voidtheart** [comment]
@101tjgus 
요거 아직 해결안된 것 같아서 다시 리오픈하겠습니다!
오늘 어플 릴리즈 관련하여 조사하면서 저것도 함꼐 보려고합니다!

**Comment by ows3090** [comment]
@voidtheart @101tjgus 선아님 서현님
해당 내용 정리가 되었을까요?
1. 카카오 약관동의 이외 자체 약관 동의 페이지 필요 여부
2. 닉네임 설정 페이지 필요 여부

위 내용 빠르게 확인 부탁드립니다.

**Comment by voidtheart** [comment]
@ows3090 
1. 자체 약관 동의 페이지는 필요합니다
2. 닉네임 설정 페이지는 필요하지 않습니다!

**Comment by 101tjgus** [comment]
@ows3090 
저흰 카톡에 등록된 이름을 쓸거라 닉네임 설정하는 페이지는 따로 필요 없습니다!

@voidtheart
선아님! 그럼 자체 약관페이지는 빼면 안되는 것으로 결정된걸까요?!

**Comment by voidtheart** [comment]
@101tjgus 
우선은 사용자분들께 약관 동의를 받아놓은게 추후 사용자 리서치 요청드리기 수월할 것 같아서 넣어두는 쪽이면 좋겠습니당..! 
뎁스 측면에서 하나 더 추가되는 부분이다보니 뺄 수 있으면 좋긴 하지만, 지금은 필요할 것 같습니다

**Comment by 101tjgus** [comment]
@voidtheart 
아하! 세심하게 알려주셔서 감사합니다!!
아까 구두로 말씀드렸듯 ux디자인 상으로도 뎁스가 하나 추가된다고 문제가 될거같지 않아서
저도 자체 약관 추가되는거 좋은 것 같습니다~!

**Comment by ows3090** [comment]
@voidtheart @101tjgus 
네 이해했습니다.
감사합니다 :)

**Comment by voidtheart** [comment]
@101tjgus 
아닙니다! 위에서도 말씀드려야했는데 핸드폰으로 치고 있어서 짧게만 작성했네요🥲

해당 약관은 언넝 작업하도록 하겠습니다

**Comment by ows3090** [comment]
@voidtheart 선아님
회원가입 완료가 4초 노출이라고 하셨는데 생각보다 4초가 오래 지속되는 것 같은 느낌이 있습니다.
다시 한번 검토 부탁드립니다.

**Comment by 101tjgus** [comment]
@ows3090 @voidtheart 
아아 4초가 좀 길군요 ㅠ
노출 시간은 제가 프로토타이핑해보고 두분께 다시 알려드리겠습니다!

**Comment by voidtheart** [comment]
@ows3090 
넵, 서현님이 확인하고 전달 부탁드릴 예정입니다!

@101tjgus 
저희 스낵바도 4초로 정의한거로 기억하는데 혹시 그것도 확인 부탁드려도 될까요?

**Comment by ows3090** [comment]
@101tjgus @voidtheart 서현님, 선아님

4초 길이 참고하시면 좋을 것 같습니다 :)

https://user-images.githubusercontent.com/34837583/214579083-861b2cd6-fff8-4dfd-9014-0a3a84e1d083.mp4

**Comment by voidtheart** [comment]
@ows3090 
오, 실제로 보니깐 4초가 생각보다 긴편이네요..! 
4초 보여주시는 용도지만 와중에 화면 생각한 그대로 나와서 대박이네요🥳 

4초 부분은 서현님과 정해서 노티 드리겠습니다!!

**Comment by 101tjgus** [comment]
@ows3090
원석님! 노출 시간 1000ms로 정하려고 합니다.
이정도면 괜찮을지 여쭤보고 싶습니다!

**Comment by ows3090** [comment]
@101tjgus 서현님 1000ms로 변경한 후 영상 보내드립니다
괜찮으시면 1초로 확정하도록 하겠습니다.

https://user-images.githubusercontent.com/34837583/214851813-81262dea-f44b-40df-952c-a90a1f3bea71.mp4

CC : @voidtheart

**Comment by voidtheart** [comment]
@101tjgus 
서현님, 약간 빠른감이 있는 것 같은데 혹시 어떠실까요? 서현님 보기에 괜찮으면 저는 좋습니담!!

**Comment by 101tjgus** [comment]
@voidtheart 앗 그런가요?! 제 눈엔 괜찮긴 한데 저는 이미 객관적인 눈을 잃은 상태라 😅 그럼 토요일 회의때 속도 조금 늘린 프로토타입 버전 같이 봐주시면 감사할 것 같습니다!

@ows3090 만약 변동사항 생기면 최소 토요일까지는 코멘트 남기겠습니다! 항상 감사드립니다 :)

**Comment by ows3090** [comment]
@101tjgus @voidtheart 선아님 서현님
시간 변경 같은 경우도 손쉬운 작업이라 추후 배포된 이후에 확인해보시다가 변경이 필요할 경우에
변경해도 괜찮습니다 :)
해당 기능은 개발 완료되어 이슈 종료부탁드립니다~

**Comment by voidtheart** [comment]
@ows3090 

오..! 그렇다면 해당 부분은 저희가 배포 이후에 한번더 고민하도록 하겠습니당 ㅎㅎ 서현님 말씀대로 이미 인지를 잘 못하고 있어서 🥲 사용성 테스트때 여쭙어도 될 것 같아요

해당 이슈 클로즈합니다!! 고생 많으셨어요 원석님 🫡
(Cc. @101tjgus )

**Comment by voidtheart** [comment]
@ows3090 
원석님, 오늘 말씀주신 부분 스토리보드 반영완료했습니다!
원석님과 저도 모두 인지하고 있는 변경사항이라서 따로 이슈를 생성하지않고,
관련 이슈에 추가로 남깁니다 :) 집어주셔서 다시 한번 감사드립니다 (초록색 부분)

변경사항 요약: 카카오계정(이메일)을 필수 수집항목으로 변경 
(cc @101tjgus)

<img width="904" alt="스크린샷 2023-01-29 오후 11 01 04" src="https://user-images.githubusercontent.com/121834419/215331266-45d0fbe3-5848-4f39-b0da-2a3ae6a7bfa1.png">
