### ISSUE TITLE
[Design] 회원가입 완료 화면 이미지 삽입

### ISSUE THREAD

**Issue by 101tjgus** [YAPP-Github/21st-Android-Team-1-Android#33]
### **위치**
회원가입 완료 화면

### **변경사항**
이미지 작업이 완료되어, 해당 이미지로 화면에 넣어주시면 감사하겠습니다 :)
![회원가입완료](https://user-images.githubusercontent.com/122163008/213621930-bdb04903-9413-49ba-8d8c-70305087569a.png)

**Comment by ows3090** [comment]
@voidtheart @101tjgus 
선아님, 서현님
카카오로 회원가입 이후 저 화면이 나오고 몇초 후에 자동으로 메인 화면으로 나오는 걸까요?

**Comment by ows3090** [comment]
@voidtheart @101tjgus 
선아님, 서현님
궁금한 점은 처음 카카오 로그인일 때는 회원가입이라고 볼 수 있겠지만
몇 일 후에 다시 로그인을 하였을 때는 회원가입이 아닐텐데 이 때도 저 화면이 노출되면 이상하지 않을까 싶습니다.
혹시 그럼 처음 로그인 시에만 저 화면을 원하시는걸까요?

**Comment by ows3090** [comment]
> @voidtheart @101tjgus 선아님, 서현님 카카오로 회원가입 이후 저 화면이 나오고 몇초 후에 자동으로 메인 화면으로 나오는 걸까요?

피그마에서 확인했습니다 :)

**Comment by ows3090** [comment]
@voidtheart @101tjgus  개발 완료되어 이슈 종료하겠습니다.
