### ISSUE TITLE
[Feature] Splash 화면 구현

### ISSUE THREAD

**Issue by ows3090** [YAPP-Github/21st-Android-Team-1-Android#37]
## 목적
> Splash 화면 구현 

## 작업 상세 내용
- [ ] Splash 레이아웃 구현
- [ ] Android 12 Splash Screen API 확인

**Comment by ows3090** [comment]
@voidtheart 선아님
Android OS 12 기기부터는 Splash 이미지가 어플 런처 이미지로 기본적으로 제공됩니다.
따라서 기본 Splash 이미지 + 저희 BuddyCon Splash 이미지가 동시에 나타나게 됩니다.
아래 동영상을 확인해보시면 토스 앱도 저렇게 나타나는 모습이 있습니다.
https://www.youtube.com/watch?v=R9NbzU94Dq0

하지만 Android OS 12 미만 기기에서는 Splash를 제공하지 않기 때문에 저희 BuddyCon Splash 이미지가 나타납니다.
여기서 2가지 애로사항이 존재합니다.

1. Android OS와 상관없이 공통적인 Splash 화면을 원한다 
- 이 경우에 저희 현재 Splash 이미지가 수정이 되어야 합니다.  Android 12 기기에서는 Icon 이미지, 배경 정도는 바꿀 수 있지만,
위치랑 크기는 변경이 힘든 것 같습니다 -> 정확하지는 않을수도 있지만.. 해결방법을 찾기 어렵네요..
- 따라서 저희 런처 이미지가 아직 없는데 해당 이미지로만 보여진후에 walk through로 진입하는게 어떤지 의견 드립니다.

2. Android 12에서만 예외사항으로 둔다.
- 현재 많은 앱들이 Android 12 Splash 예외처리를 하지는 않고 있습니다.
- 그래서 해당 기기에서만 런처이미지 후에 저희 BuddyCon Splash 나오도록 될 것 같습니다.

빠르게 확인 부탁드립니다.
https://sungbin.land/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C12-%EC%8A%A4%ED%94%8C%EB%9E%98%EC%8B%9C-%EB%8C%80%EC%9D%91%ED%95%98%EA%B8%B0-1729f69dc33f

**Comment by voidtheart** [comment]
@ows3090 
오... 해당 부분을 전혀 모르고 있었는데 공유 감사합니다..!
말씀하신 1번이 런처 이미지 > walk through로 바로 넘어가는 플로우를 의미하시는게 맞으실까요?

2번 방안 같은 경우, 안드로이드 12만 따로 예외처리하는게 어려울 것 같아보여서 
1번이 개발하실 때 그나마 덜 고생하실 것 같고,
1번이 해당 플로우로 이루어지는게 맞다면 런처로 대체해도 될 것 같아서요!

**Comment by ows3090** [comment]
@voidtheart 선아님
말씀하신 내용이 맞습니다.
저도 2번 Splash 이미지가 노출되는 것보다는 1번 노출되는 것이 맞아보입니다.

다만 런처이미지로 할 경우 아래와 같은 이미지는 하기 힘든점 참고 부탁드립니다.
![image](https://user-images.githubusercontent.com/34837583/214070628-683ef07b-68f5-4cbe-8070-50a6744e1c58.png)
런처 이미지의 위치, 크기가 정해져서 해당 타이틀 문구는 어려울 것 같습니다.

**Comment by voidtheart** [comment]
@ows3090 
헉 빠른 확인 감사합니다 원석님! 
아하! 저는 그렇다면 1번으로 진행하는게 맞을 것 같습니다..!
스플래쉬가 2번 보이는거보다는 조금 안이쁘더라도 (?) 한번만 보이는게 사용성 측면에서도 나을 것 같아서요

@101tjgus 
서현님, 1번으로 스플래쉬 형태가 변경되어도 괜찮을까요? 최종 시안은 개발 이후 확인 가능할 것 같습니다 :)

**Comment by 101tjgus** [comment]
확인했습니다!
두번 뜨는건 오류같기도 하고 되게 부자연스러워보이네요.. 저도 1번이 좋을 것 같습니다!
런처 이미지를 스플래쉬에 나오는 로고와 같은 타이포그래피로 제작할 예정이었어서, 더더욱 상관없을 것 같습니다!

꼼꼼하게 짚어주셔서 감사합니다 :)

**Comment by ows3090** [comment]
@101tjgus 서현님
서현님 런처이미지를 스플래쉬와 같은 로고로 하게 될 경우에 문제가 발생할 수도 있습니다.
기존에 제작된 Splash 이미지의 BuddyCon을 넣게 될 경우 크기로 인해 짤리게 되었습니다.
크기를 줄이게 되면 글자자체가 잘 보이지 않더라구요
https://developer.android.com/develop/ui/views/launch/splash-screen

위 링크에서 Gmail 스플래쉬처럼 딱 가운데 중앙에 위치해 있고 원모양으로만 보여지게 됩니다 (Android 12)
참고 부탁드려요!~
CC : @voidtheart

**Comment by voidtheart** [comment]
@ows3090 
꼼꼼하게 알아봐주셔서 감사합니다 원석님 :)
서현님이랑 지금 만나서 회의중인데, 괜찮으시다고 구두로도 저한테도 말씀주셔서 
1번 방안으로 개발 진행해주시면 감사하겠습니다 ! 화이팅임다!

**Comment by 101tjgus** [comment]
@ows3090 아하 그렇군요...!! 알려주셔서 감사합니다
그럼 보내주신 가이드 참고해서 런처이미지, 스플래시 이미지 전달드리도록 하겠습니다!

**Comment by 101tjgus** [comment]
@ows3090 
원석님, 런처 이미지가 앱아이콘으로 보여지는 모습 뿐만 아니라 스플래시 화면으로도 겸해야함에 따라 고민할 시간이 조금 더 필요할 것 같습니다 ㅜㅜ (가시성 면에서)

정확하지는 않지만 현재는 버디콘 캐릭터 이미지로 제작할까 생각중입니다.

이번주 일요일 회의날까지 전달드리는걸 목표로 고민해서 화면 전달드리겠습니다!

**Comment by ows3090** [comment]
@101tjgus 서현님
이미지 변경은 정말 손쉽게 하는 작업이라 천천히 주셔도 됩니다 ^^
