### ISSUE TITLE
[PLAN] 기프티콘 & 제작티콘 - 사용가능탭 칩 표시 스펙 

### ISSUE THREAD

**Issue by voidtheart** [YAPP-Github/21st-Android-Team-1-Android#38]
### 위치 
1. 홈 (기프티콘) - 기프티콘 메인화면 - 기프티콘 메인화면 : 사용가능 탭
2. 제작티콘 메인화면 : 사용가능 탭 (default) - 제작티콘 메인화면 : 사용가능 탭

### 공유사항  
1. 기프티콘 - 사용가능탭에서 D-0~14 의 유효기간이 남은 쿠폰들만 칩이 표시됩니다. 
2. 제작티콘 - 사용가능탭에서 D-0~14 의 유효기간이 남은 쿠폰들만 칩이 표시됩니다. 

### 기대효과
1. 기프티콘 - 사용가능탭에서 D-0~14 의 유효기간이 남은 쿠폰들만 칩이 표시됩니다. 
- D-15이상의 유효기간이 남은 쿠폰들은 칩이 표시되지 않습니다.

2. 제작티콘 - 사용가능탭에서 D-0~14 의 유효기간이 남은 쿠폰들만 칩이 표시됩니다. 
- D-15이상의 유효기간이 남은 쿠폰들은 칩이 표시되지 않습니다.

<img width="773" alt="스크린샷 2023-01-22 오후 7 13 03" src="https://user-images.githubusercontent.com/121834419/213910698-e9158a30-6a58-48be-8c9c-0dd689d3aaa7.png">

### 참고사항
초반에 스토리보드 공유드렸을 때부터 기디에서 합의된 내용이었는데, 
오늘 스토리보드 하나씩 훏어보다가 해당 내용에 대한 설명이 빠진 것 같아서 공유드립니다. 
(기존에는 D - 0~7, 8~14가 어떤 색깔의 칩으로, 어떤 상황에서 뜨는지 적어놓아서 아마 개발하시면서 문제 없었을 것 같습니다.)
노파심에 공유드리니 참고만 부탁드릴게요!)

**Comment by voidtheart** [comment]
@ows3090 확인하신 다음 클로즈하셔도 무방합니다

**Comment by voidtheart** [comment]
@Huey-J @shinyubin989
혹시 몰라서 공유드립니담

**Comment by ows3090** [comment]
@101tjgus @voidtheart 서현님, 선아님
해당 이슈는 개발 완료되어서 클로즈 해주셔도 되고, 기한 만료된 부분만 별도 이슈로 공유 부탁드립니다.

**Comment by voidtheart** [comment]
@ows3090 
원석님, 어제 논의하신 ! < 요거 말씀하시는거 맞으실까요? 맞으면 바로 클로즈하도록 하겠습니다!
아직 gui 작업 중인거로 알아서 완료되는대로 별도 이슈로 공유드리겠습니다 :)

**Comment by ows3090** [comment]
@voidtheart 네 맞습니다 선아님

**Comment by voidtheart** [comment]
넵 확인하여 클로즈합니다!
