### ISSUE TITLE
[PLAN] 버디콘 공통사항 - 쿠폰 삭제 기능 정의 

### ISSUE THREAD

**Issue by voidtheart** [YAPP-Github/21st-Android-Team-1-Android#43]
## 위치
버디콘 공통사항 - 쿠폰 삭제 기능

## 공유사항 
공통사항인데 디스크립션 작성을 누락해서 지금 공유드립니다 

## 기대효과
1. '삭제'를 누르면 삭제 다이얼로그가 노출됩니다.
- '확인'을 눌러서 해당 기프티콘/쿠폰을 삭제할 수 있습니다

<img width="804" alt="스크린샷 2023-01-22 오후 11 31 28" src="https://user-images.githubusercontent.com/121834419/213921455-f7444eaf-1ced-4792-beb5-a5094ab22cd7.png">

## 참고사항
해당 이슈는 확인 이후 클로즈하셔도 됩니다
(원석님 파트 같아서 태깅합니다)

**Comment by voidtheart** [comment]
@Huey-J @shinyubin989 
기존에 gui와 스토리보드 상에 존재하지만,
따로 디스크립션을 작성하는걸 깜박하여 공유드립니다 :) 참고부탁드려용

**Comment by ows3090** [comment]
@voidtheart 확인했습니다 이슈종료할게요!
