### ISSUE TITLE
[Design] 제작티콘 홈 - '아직 공유하지 않은 쿠폰' 문구 변경

### ISSUE THREAD

**Issue by 101tjgus** [YAPP-Github/21st-Android-Team-1-Android#48]
### **위치**
제작티콘 홈 - 만든 쿠폰

### **변경사항**
아직 공유하지 않은 쿠폰은 딤처리와 함께 '아직 공유하지 않은 쿠폰입니다' 문구로 표시합니다.
여기 문구를 '공유'대신 '선물'로 대체해주시면 감사하겠습니다.

**as is - '아직 공유하지 않은 쿠폰입니다'
to be - '아직 선물하지 않은 쿠폰입니다'**
![제작티콘_만든쿠폰](https://user-images.githubusercontent.com/122163008/213977018-79783b7f-a90a-4b1f-a099-a13c4d4f98ca.png)

### **기대효과**
유저가 일관된 UX-Writing 경험을 할 수 있습니다.

**Comment by voidtheart** [comment]
@101tjgus 
헉 ㅋㅋㅋㅋㅋㅋㅋ 저도 이거 작성했는데, 서현님꺼가 자세하네요. 
제껀 중복이니깐 클로즈할게요~!

**Comment by ows3090** [comment]
@101tjgus 서현님 
이거 "선물" 텍스트로만 변경하면 되는걸까요?

**Comment by voidtheart** [comment]
@ows3090 
서현님 대신 답변드립니다!
선물로만 텍스트 변경하면 됩니다!!!

**Comment by voidtheart** [comment]
해당 이슈 클로즈합니당!
(이후 재확인 필요)
