### ISSUE TITLE
[PLAN] 제작티콘 만들기 '기본 이미지로' 버튼 생략

### ISSUE THREAD

**Issue by 101tjgus** [YAPP-Github/21st-Android-Team-1-Android#59]
### **위치**
제작티콘 만들기에서 '이미지 불러오기', '기프티콘 불러오기' 누른 이후 페이지

### **변경사항**
제작티콘 만들기에서 '이미지 불러오기', '기프티콘 불러오기'를 누르면
두 경우 모두 **'기본 이미지로', '이미지 변경하기'** 이렇게 두 버튼이 뜨게 됩니다.

여기에서 '기본 이미지로' 버튼을 없애고 **'이미지 변경하기'만 존재**하는 방향으로 수정 요청 드립니다.

![기프티콘만들기_플로우](https://user-images.githubusercontent.com/122163008/215328697-0a3b00c2-5d02-41c8-8da8-0e6aeda629d2.PNG)

1. 버튼 :
- 맨 처음 진입시 **'이미지 불러오기' ' 기프티콘 불러오기'** 
- 이미지를 불러왔을 경우 **'이미지 변경하기'**
- 기프티콘을 불러왔을 경우 **'이미지 변경하기'**

2. 기본 이미지로 돌아가고 싶은 경우 : 테마 미리보기 이미지 선택

### **기대효과**
타 서비스를 살펴본 결과,
테마의 디폴트 이미지로 돌아갈 때는 해당 테마를 다시 클릭하는 플로우가 익숙하다는 것을 확인할 수 있었습니다.
따라서 현재의 '기본 이미지로' 라는 버튼이 존재하는 것은 익숙하지 않은 사용자 경험이라는 판단이 들었습니다.
(버튼으로 따로 나와있을만큼 기본 이미지로 돌아가는 기능이 자주 쓰는 기능도 아니었습니다...ㅜㅜ)

해당 버튼을 생략할 경우, UI가 직관적으로 보여져 이미지를 변경하는 과업 수행에 있어서 조금 더 수월해질 것으로 예상됩니다.
또한 GUI가 더 깔끔해지고 버튼명이 헷갈릴 일을 방지할 수 있을 것이라 기대됩니다.

### **참고사항**
피그마 '디자인 최종' 페이지에서
'제작티콘 만들기' 열 맨 왼쪽에 내용, 변경 UI 정리해두었습니다.

**Comment by 101tjgus** [comment]
CC @voidtheart

**Comment by voidtheart** [comment]
@101tjgus 
정리 감사합니다 서현님!
해당 부분 스토리보드에도 반영하면 될까용?! :)

**Comment by ashwon12** [comment]
@101tjgus  @voidtheart 
변경 사항 확인했습니다. 
그러면 한번 기프티콘을 불러오거나 이미지를 불러왔을 때 반대되는 액션을 취하고 싶으면 뒤로갔다가 다시오는 방법으로 진행되는게 맞나요?!

**Comment by 101tjgus** [comment]
@ashwon12 
- 기프티콘 불러오기 취소, 기프티콘 변경하기 : 뒤로가기
- 이미지 변경 : 이미지 하단의 ’이미지 변경하기‘ 버튼 누르기
- 기본 이미지로 변경 : 펼친 테마에서 미리보기 이미지 누르기

@voidtheart 저는 이렇게 이해하고 있는데, 선아님는 어떠실까요?!

**Comment by 101tjgus** [comment]
@ashwon12 재원님, 그럼 해당 변경사항에서 큰 문제는 없는걸로 이해하면 될까요? :) 
혹시 어색하거나 우려되는점 있으시다면 알려주시면 감사하겠습니다!

**Comment by voidtheart** [comment]
@101tjgus 
저도 서현님이 말씀하신 스펙과 동일하게 이해하고 있습니다!!

**Comment by ashwon12** [comment]
넵 변경사항대로 진행하겠습니다~~ !!!!

**Comment by 101tjgus** [comment]
@voidtheart 선아님 이대로 스토리보드 반영해주시면 될 것 같습니다 :) 피그마 디자인최종 페이지에 완성된 ui 배치해두었습니다!
