### ISSUE TITLE
[Share] Firebase 테스트 앱 배포를 통한 기획/디자이너 분들에게 공유

### ISSUE THREAD

**Issue by ows3090** [YAPP-Github/21st-Android-Team-1-Android#60]
## 어떤 기능을 위한 것인지
> Firebase App Distribution 을 이용하여 테스트 앱 배포

## 구현 과정
- Firebase SDK 연동
- 테스터 메일 추가

### 참고 사항
테스트할 기기에서 메일 확인하시고 절차대로 확인하시면 app을 다운로드 받으실 수 있습니다.
![image](https://user-images.githubusercontent.com/34837583/215469883-d7910caa-e634-42bd-a26e-3929bdb8f80c.png)

참고로 갤럭시에서 외부에서 받은 파일을 설치 못하게 할 수도 있는데 설정가서 바꾸실 수 있습니다.
하시다가 모르시면 말씀 부탁드립니다.

그리고 테스트앱 배포는 확인해보고 싶으실 때 저희에게 요청을 드리면 현재 개발한 내용까지는 전달드릴 수 있으며, 그 외에는 기능별로 공유드려야할 경우에 배포 후 코멘트 드리겠습니다 
@ashwon12 @hanchang97

**Comment by ows3090** [comment]
@voidtheart @101tjgus  선아님, 서현님
테스트 앱 배포를 위해 메일 계정 공유 부탁드립니다.
추후 기능 개발 후에 테스트 앱을 메일로 전달되고 다운로드 받으실 수 있습니다.
자세한 사항은 가이드 문서 작성하겠습니다

**Comment by voidtheart** [comment]
헙… 개발 하신다고 넘 바쁘신데 세세하게 신경써주셔서 감사합니다! 🥳

선아: voidtheart@gmail.com 
서현: 101tjgus@gmail.com
(서현님, 요거로 알고 있는데 확인 부탁드릴게요! cc @101tjgus )

**Comment by ows3090** [comment]
@voidtheart 선아님
메일로 테스트앱 공유드렸는데 확인 가능하실까요?

**Comment by 101tjgus** [comment]
@voidtheart 오 그거 맞습니다!! 감사합니다

**Comment by ows3090** [comment]
@voidtheart @101tjgus 선아님, 서현님 메일 확인 부탁드리며 테스트도 한번 부탁드립니다.
그리고 현재 이슈를 가지고 앱 배포 히스토리 관리를 하면 좋을 것 같아요
기획/디자이너 분들께서 필요하실 때 요청도 여기서 하고 개발자 분들도 테스트앱 배포 시에 여기에 공유드리면 좋을 것 같습니다.

그리고 @ashwon12 @hanchang97 창희님, 재원님 저희는 PR 단위로 테스트 앱을 배포할 필요는 없을 것 같고 기획/디자이너 분들께 공유드려할 경우나 어느정도 큰 기능이 개발되었을 때 드리면 될 것 같아요!

**Comment by 101tjgus** [comment]
@ows3090 넵 메일은 잘 받았습니다! 이따가 테스트 해보고 다시 코멘트 드릴게요! 감사합니다 :)

**Comment by voidtheart** [comment]
@ows3090 
원석님, 카카오 로그인 동의화면까지 확인 완료했습니다! 
제가 안드로이드이 안 익숙하다보니 이래저래 헤매서 (...) 
조금 오래 걸렸는데 앞으로 요렇게 기디단에서도 확인하면 될 것 같습니당 :) 

그렇다면 말씀하신대로 이슈 페이지에서 그럼 히스토리 관리하는거로 할까요?
이용약관과 같은 서류를 위한 노션 페이지를 생성하면서 
히스토리 업데이트도 보여줄 수 있도록 아예 노션을 파려고 하고 있긴 합니다..!! 
근데 아무래도 요건 외부용이라서 내부용도 있으면 좋을 것 같습니다!
공유드린 링크 느낌만 참고 부탁드립니다

![IMG_6631](https://user-images.githubusercontent.com/121834419/215492152-fb7109fd-6f23-4bbf-a6ed-9f3ea7a9eb42.JPG)
<img width="798" alt="스크린샷 2023-01-30 오후 10 38 17" src="https://user-images.githubusercontent.com/121834419/215492597-7cf05bb4-e28a-440b-b3d8-0e27de6d63eb.png">
[노션 - 어플 히스토리 예시](https://www.notion.so/Version-Update-62090717dd1c43f0bde7264c48f3c1ba)

**Comment by voidtheart** [comment]
추가로 이용약관/개인정보 처리방침 문서가 끝난 다음,
시간적으로 가능하면 아래와 같은 QA sheet를 기획단에서 생성하여
QA 진행하면 좋을지 의견 여쭙고자 합니다!

(우선은 심사 신청과 QA가 동시에 진행될 예정이기도 하고,
기획단에서도 문서 작성이 우선순위가 높아서 
메인으로 작업하고 이번주 주말 ~ 다음주 월화 사이 끝내려고 합니다.)


<img width="1786" alt="스크린샷 2023-01-30 오후 10 41 42" src="https://user-images.githubusercontent.com/121834419/215493375-8f7dc51b-718f-4e92-9bdf-e40cf73a23bc.png">

**Comment by 101tjgus** [comment]
@ows3090 
설치해서 확인했습니다 :) 감사드려요
그럼 이곳에 업데이트 되는 화면들은 모두 완성된거라고 보면 될까요?! 아니면 아직 완성도보다는 기능 위주로 봐야하는걸까요? 디자인 수정 요청은 어느 시점부터 드리면 좋을지 궁금해서 여쭙습니다

**Comment by ows3090** [comment]
@101tjgus 서현님
기능, 화면 모두 개발하였습니다.
디자인 수정 요청은 혹시 별도로 관리하셨다가 1차 배포 이후에 해도 괜찮을까요?
만일 모든 수정 요청을 이슈로 관리하면 복잡할 것 같아서요

**Comment by 101tjgus** [comment]
@ows3090 
네! 그럼 마이너한 디자인 요청사항은 구글시트나 노션에 따로 정리하고, 중요한 요청사항은 지금처럼 깃헙에 이슈로 업로드 하겠습니다! 문서는 생성하면 링크 전달드릴게요!!
