### ISSUE TITLE
[Design] 로그인화면 로고 형식 변경

### ISSUE THREAD

**Issue by 101tjgus** [YAPP-Github/21st-Android-Team-1-Android#62]
### **위치**
로그인 화면

### **변경사항**
기기에 따라 로고가 다르게 보이는 일을 방지하기 위해
고정적인 벡터 이미지로 변경했습니다.

![버디콘_로그인](https://user-images.githubusercontent.com/122163008/215530611-482455ff-228d-4690-be56-1049c8e7f574.PNG)
로고는 프레임에 가두어 컴포넌트로 제작해서 대체 완료했습니다.
디자인 최종, 스토리보드 화면 모두 수정한 화면으로 변경해 두었습니다.

### **기대효과**
기기에 따라 로고가 다르게 보이는 일을 방지할 수 있습니다.

![버디콘_로그인_피그마](https://user-images.githubusercontent.com/122163008/215531797-a72a2ac5-4c0a-4f49-8f4f-a0ff554d954d.PNG)
(처음부터 벡터 형식으로 제작해서 드렸어야 했는데, 저의 불찰입니다...)

**Comment by ows3090** [comment]
@101tjgus 서현님 내용인지 하였고 현재 개발하는 것까지 완료한 후에 수정하도록 할게요

**Comment by voidtheart** [comment]
정상적으로 반영되었음을 확인하여 클로즈합니다!
