### ISSUE TITLE
[DESIGN] 앱아이콘 디자인 완료

### ISSUE THREAD

**Issue by 101tjgus** [YAPP-Github/21st-Android-Team-1-Android#75]
앱아이콘 디자인 완료되어 전달드립니다.
![앱아이콘](https://user-images.githubusercontent.com/122163008/217449233-98d72e5f-fa33-49c8-b894-e88be13d7251.PNG)
피그마 - [디자인 가이드] 페이지에 두었습니다.

512*512 사이즈로 제작했으며
시작 화면도 해당 이미지로 뜨면 될 것 같습니다!
혹시 잘리는 등의 문제가 있거나 다른 사이즈로 변환이 필요하다면
언제든 편하게 요청주세요!!

**Comment by ows3090** [comment]
@101tjgus 서현님
<img width="250" src="https://user-images.githubusercontent.com/34837583/218326327-16a1cb57-4dfa-4952-812f-8c099f2456ad.png"/>
앱 런처 아이콘은 잘 나오는데 스플래쉬 화면 경우에 위처럼 나옵니다.
아마 스플래쉬 이미지가 강제적으로 원형으로 크롭되는 것 같습니다.
이미지를 조금 작게하면 될 것 같긴한데 이미지를 제가 직접 줄여도  괜찮을지 문의드립니다(CC : @voidtheart )

**Comment by voidtheart** [comment]
@ows3090 
넵! 저는 원석님이 괜찮으시면 확인해보시면서 줄여도 될 것 같습니다!! 
괜찮으실까요 서현님?! @101tjgus

**Comment by 101tjgus** [comment]
@ows3090 어이쿠.. 가이드에 맞게 제작했는데도 잘리네요....
이미지 축소해주시면 감사하겠습니다 :D

**Comment by ows3090** [comment]
@101tjgus 서현님
![image](https://user-images.githubusercontent.com/34837583/218522929-dbd0f927-250c-4b16-8636-f116dea509e5.png)
제가 수정하기가 조금 어려울것 같습니다 ㅠㅠ
혹시 아이콘 이미지 원형으로 하나 더 만들어 주실 수 있나요?
skb_blue 원형 배경에 이미지가 포함된 형식으로 부탁드립니다.

**Comment by 101tjgus** [comment]
@ows3090 원석님! 원형 아이콘을 어떤 사이즈와 형식으로 만들어야 할지 잘 모르겠어서
우선 여러 버전으로 제작해봤습니다.
![캡처_로고_깃헙](https://user-images.githubusercontent.com/122163008/218952328-9e09fa99-dc2a-4100-a7fb-0ed261f67369.PNG)

피그마에서 런처 아이콘과 동일한 위치에 두었고,
혹시 정확한 사이즈로 제작이 필요하시다면 말씀주세요! 
최대한 빨리 다시 제작해서 전달드리겠습니다 :)

**Comment by ows3090** [comment]
@101tjgus 서현님
반영 완료 했습니다 :)

**Comment by voidtheart** [comment]
정상적으로 반영되었음을 확인하여 클로즈합니다!
