### ISSUE TITLE
[Question] Drawable 리소스 해상도 대응

### ISSUE THREAD

**Issue by ows3090** [YAPP-Github/21st-Android-Team-1-Android#8]
## 문제
>  Drawable 리소스 해상도별로 개발 어떻게 하셨는지 궁금해요!
벡터 이미지로 하셨는지 특정 타겟 디바이스 기준으로 하셨는지 아니면 모든 해상도별 이미지를 추가하셨는지 궁금합니다.
저희 회사에서는 하나의 해상도만 타겟하다보니 이 처리를 어떻게 했는지 궁금하네요

**Comment by hanchang97** [comment]
@ows3090 벡터가 아닌 형태로 이미지를 사용해야 하면 해상도별 리소스 폴더를 나눴습니다!!
벡터는 그대로 사용했고요

**Comment by ows3090** [comment]
@hanchang97 
둘다 사용가능하면 벡터 이미지를 사용하신거죠~?

**Comment by ashwon12** [comment]
저는 최대한 벡터 이미지로 drawable 추가해주었고 없으면 그냥 png 파일 써서 개발한 경험만 있습니다!
따로 해상도별로 이미지를 추가하지는 않았고 디바이스 기준으로 최대한 맞춰서 png로 처리했습니다.

**Comment by ows3090** [comment]
@ashwon12  @hanchang97 
넵 의견 확인했습니다~ 이슈 종료할게요!!
