### ISSUE TITLE
[Feature] Design 세부조정 

### ISSUE THREAD

**Issue by ows3090** [YAPP-Github/21st-Android-Team-1-Android#86]
## 목적
개발 이후 필요한 Design 세부조정 및 변경

## 작업 상세 내용
- [x] #48 
- [x] #26 
- [x] #84 
- [ ] #81 
- [x] #75 
- [x] #62 
- [x] #89 
- [x] #92

**Comment by ows3090** [comment]
@101tjgus @voidtheart 서현님, 선아님
여기에서 1차로 Design 관련 수정들 모두 반영할게요

**Comment by voidtheart** [comment]
@101tjgus 
테스트 어플 v2.0 공유주신거로 알고 있어서 오늘 기디에서 보고 추가사항 있으면 전달드리겠습니다!

**Comment by 101tjgus** [comment]
@ows3090 @voidtheart 
오늘이나 내일 쯤 한번에 확인해보고 수정사항 전달드리겠습니다! 
고생 많으셨습니다 !!

**Comment by voidtheart** [comment]
@ows3090 
원석님, 전체적으로 다 클로즈하였으며, 수정하신다고 고생 많으셨습니다 :) 
이후 재확인이 필요한 부분들은 recheck / 작업이 필요한 부분들은 backlog로 태깅 완료했습니다
(필요한 경우 이후 재 오픈하겠습니당ㅎㅎ)
