### ISSUE TITLE
[PLAN] 서비스 이용약관 / 개인정보방침처리 노션링크 공유 

### ISSUE THREAD

**Issue by voidtheart** [YAPP-Github/21st-Android-Team-1-Android#92]
회원가입 진행 시, 동의받는 서비스 이용약관과 개인정보방침처리 문서 전달드립니다!
버디콘 공식 노션페이지는 현재 작업중에 있으며 
두가지 문서의 하이퍼링크만 화면에 걸어주시면 됩니다! 
(개발과 동일하게 1차 배포 이후 노션페이지는 꾸밀 예정이니 참고부탁드립니다ㅠㅠ)

[서비스 이용약관](https://scarce-cartoon-27d.notion.site/5567225d323c46d9bc7bd11909453031)
[개인정보방침처리](https://www.notion.so/d9ddfff97a064ebaa0d4b4ce3d01e23c?pvs=4)

@ows3090 
원석님, 회원가입 페이지에 > 누르면 해당 링크로 넘어갈 수 있도록 추가해주시면 감사하겠습니다 :)
<img width="546" alt="스크린샷 2023-02-14 오전 1 40 01" src="https://user-images.githubusercontent.com/121834419/218518926-d44564dc-5d36-4fce-8030-ab5a036e8a46.png">

@ashwon12
재원님, 추후 마이페이지 개발완료되면 링크 걸어주시면 됩니다 :)
(1차에서 마이페이지
<img width="331" alt="스크린샷 2023-02-14 오전 1 40 27" src="https://user-images.githubusercontent.com/121834419/218518974-e8532252-87f0-4566-9d91-09430d8ff699.png">
는 없을 예정이긴한데 미리 공유드립니다!)

**Comment by ows3090** [comment]
@voidtheart 선아님
약관, 동의화면 링크 추후  open 할 생각이신건가요?

**Comment by voidtheart** [comment]
@ows3090 
원석님, 마이페이지 작업 어느정도 진행되었으면 연결해주시면 좋을 것 같고 / 아직 작업중이면 스킵하셔도 됩니다! 우선 로그인 - 동의화면에서는 노션 링크 open 부탁드립니다

**Comment by ows3090** [comment]
@voidtheart 선아님
해당 기능 개발 하는 방식은 총 3가지가 있습니다.
1. 테스트 앱 배포 드린 방식으로 앱 내 자체적으로 웹 페이지를 띄우는 방식
2. 크롬/인터넷 브라우저 별도의 앱 선택 후 새로운 앱을 열어서 웹 페이지를 띄우는 방식
3. 자체 네이티브 UI 개발

자체 네이티브 UI 개발은 지금과는 완전히 다른 빠른 렌더링이 가능합니다.
다만, 피그마로 UI 작업을 명시적으로 해주셔야만 제가 편하게 작업이 가능할 것 같습니다.
취사선택 해주셔서 말씀 부탁드립니다.

**Comment by voidtheart** [comment]
@ows3090 
오..! 사실 가장 베스트는 자체 네이비브 UI 개발이긴한데, 
개발 일정상 빠듯하고 우선순위가 낮아서 노션을 이용해서 띄우는 스펙으로 잡게 되었습니다..ㅎㅎ..
근데 저도 지금 확인해보니깐 확실히 느리긴하네요 ㅠㅠ

알림 기능 - 알림 세부 페이지 ui를 활용하면 될 것 같은데, 요건 서현님께 제가 내일 한번 여쭤보겠습니당!! 
(혹시라도 다른 ui가 나을지 확인하기 위함)

요건 사용성 문제에 가까운 것 같아서 천천히 작업하는거로 하겠습니다!! 
<img width="678" alt="스크린샷 2023-02-17 오전 1 00 21" src="https://user-images.githubusercontent.com/121834419/219420326-d125a7e4-9c9b-4ace-9d0c-79b0bc5b0ac2.png">

**Comment by ows3090** [comment]
@voidtheart @101tjgus 
넵 네이티브 UI 작업도 엄청 어려운건 아니라서 피그마 작업만 완료되면 공유주세요

**Comment by voidtheart** [comment]
요거는 디자인 gui 작업되는대로 공유드리겠습니다 (__)

**Comment by voidtheart** [comment]
@101tjgus 
서현님! 요거 나중에 gui 작업 부탁드리겠습니다!! 
(약관에서는 크게 title, subtitle, body로 이루어질 것 같아요)

요건 기디때 한번 짧게 얘기해보면 좋을 것 같습니당
