### ISSUE TITLE
[Question] 게스트 로그인 임시 제공 여부

### ISSUE THREAD

**Issue by voidtheart** [YAPP-Github/21st-Android-Team-1-Android#96]
## 관련된 기능
> 로그인/회원가입 

## 문제
> 현재 플레이스토어 심사 신청 시, 테스트 계정이 필요합니다. 
저희 같은 경우, 카카오톡 소셜 로그인만 존재하므로 카카오 테스트 계정이 필요한데 
카카오 측에서는 이러한 계정을 별도로 제공하지 않고 있는 것으로 보입니다.
(해외 번호 어플과 교환학생 떄 사용했던 계정을 통해서 새로운 아이디 생성을 시도했는데 
모두 회원가입 인증에서 막혀서 아이디 생성이 불가능합니다. 해외번호를 통한 방식은 우선 막힌것으로 보입니다)

일반적으로 회사에서는 별도의 계정을 생성하여 테스트 계정으로 두고 있는 것 같은데,
저희는 일단 해당사항이 어려워서 얍측에 문의 드려보았습니다..! 
(참고로 제가 여쭤본 pm분들은 아직 심사 신청 전이라서 해당 테스트 계정에 대해서 모르시고 계십니다)

얍측에서 준 두가지 방법 중에서 첫번째는 별도의 번호로 아이디 생성, 두번째는 게스트 로그인을 심사시에만 표시가 있었는데
혹시 두번째 방법 관련해서는 어떻게 생각하시는지 여쭙고자 합니다..!

해당 부분 미리 고려해야했는데, 제가 제대로 알고 있지못해서
심사에 차질 생긴 점 미리 사과드립니다 ㅠㅠ 

### 참고 사항
<img width="820" alt="스크린샷 2023-02-19 오후 5 51 36" src="https://user-images.githubusercontent.com/121834419/219938303-5e267308-26c4-4d6c-9a93-202288904207.png">

**Comment by ows3090** [comment]
@voidtheart @101tjgus 선아님, 서현님
해당 기능은 저희 메인코드에 반영되었고 테스트 해보시고 안되시면 말씀해주세요

**Comment by voidtheart** [comment]
@ows3090 
원석님, 정상적으로 작동함을 확인했습니다! 기디 회의가 지금 끝나서 지금 심사 신청하고 있습니다 감사합니다!!
급작스럽게 요청드리고 기디에서 정확하게 스펙을 정의드리지못했는데 작업해주셔서 다시 한번 정말 (ㅠㅠㅠ) 감사드립니다

**Comment by voidtheart** [comment]
정상완료함을 확인하여 클로즈합니다(__)
